name: MetaGanga
version: '${project.version}'
main: me.abhinav.metaganga.Main
api-version: 1.19
depend: [PlaceholderAPI, Multiverse-Core]
commands:
  setminplayers:
  metagangareload:
  addpoints:
  forcestop:
